apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cosign-cli-2-2-nudges
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cosign-cli-2-2-nudges
    app.kubernetes.io/part-of: sigstore-nudges
  name: cosign-cli-2-2-nudges
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: cosign-cli-2-2-nudges
status:
  loadBalancer: {}
