apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: client-server-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: client-server-1-0-gamma
    app.kubernetes.io/part-of: sigstore-nudges
  name: client-server-1-0-gammakp7s
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: client-server-1-0-gamma
    weight: null
status: {}
